# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{polaris}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shawn Anderson"]
  s.date = %q{2010-02-27}
  s.description = %q{A* pathfinding in Ruby, using C datastructures to speed things up.}
  s.email = %q{shawn42@gmail.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "README.txt",
     "Rakefile",
     "VERSION",
     "lib/line_of_site.rb",
     "lib/polaris.rb",
     "lib/two_d_grid_location.rb",
     "lib/two_d_grid_map.rb",
     "polaris.gemspec",
     "spec/helper.rb",
     "spec/line_of_site_spec.rb",
     "spec/polaris_spec.rb"
  ]
  s.homepage = %q{http://github.com/shawn42/polaris}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{polaris}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A* pathfinding in ruby.}
  s.test_files = [
    "spec/helper.rb",
     "spec/line_of_site_spec.rb",
     "spec/polaris_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<algorithms>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<algorithms>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<algorithms>, [">= 0"])
  end
end

